require_relative "../core/add_author"
require_relative "../core/add_image"
require_relative "../core/add_quote"
require_relative "../core/add_user"
require_relative "../core/get_authors"
require_relative "../core/get_quotes"
require_relative "../core/user_dislikes_quote"
require_relative "../core/user_likes_quote"
